logging:
  config: classpath:logback.xml

server:
  port: 3000
  error:
    whitelabel:
      enabled: true
  servlet:
    context-path: /

spring:
  devtools:
    restart:
      additional-paths: "src/main/resources/templates"
      additional-exclude: "**/*.js,**/*.scss,**/*.css,**/*.tsx,**/*.map"

handlebars:
  charset: UTF-8
  prefix: classpath:dist/
  resolver:
    method: true
    field: true

---

spring:
  profiles: local
      
handlebars:
  cache: true

---

spring:
  profiles: default
  
handlebars:
  cache: false
  
---

spring:
  profiles: production
      
handlebars:
  cache: false
